name: Convert Conf Files

on:
  schedule:
    - cron: "0 1 * * *" # every day
  workflow_dispatch:

jobs:
  convert_conf_files:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: pip3 install glob2

    - name: Convert Conf Files
      env:
        CN_DNS: ${{
#阿里DNS(Alidns)
tls://dns.alidns.com
https://dns.alidns.com/dns-query 
quic://dns.alidns.com 
h3://dns.alidns.com/dns-query
#腾讯DNS(DNSPod)
tls://dot.pub
https://doh.pub/dns-query
#360DNS
tls://dot.360.cn
https://doh.360.cn/dns-query
}}
        THE_DNS: ${{
#Google DNS
tls://dns.google
https://dns.google/dns-query
h3://dns.google/dns-query
#OpenDNS
tls://dns.opendns.com
https://doh.opendns.com/dns-query
#Quad9 DNS
tls://dns11.quad9.net
https://dns11.quad9.net/dns-query
#AdGuard DNS
tls://dns.adguard-dns.com
https://dns.adguard-dns.com/dns-query
quic://dns.adguard-dns.com
h3://dns.adguard-dns.com/dns-query
#NextDNS
tls://Statego-9a6c54.dns.nextdns.io
https://dns.nextdns.io/9a6c54/Statego
quic://Statego-9a6c54.dns.nextdns.io
h3://dns.nextdns.io/9a6c54/Statego
}}
      run: python convert.py

    - name: Check for changes
      run: |
        if ! git diff --quiet; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          current_time=$(date +'%Y-%m-%d %H:%M:%S')
          git add .
          git commit -m "Convert conf files to txt - $current_time"
        else
          echo "No changes to commit."
        fi

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
